// Reads call summaries from Gong's v2 API. Uses Basic Auth with an Access Key
// / Secret pair (Gong's standard API credential type, generated by a Gong
// admin under Company Settings → Ecosystem → API).
//
// Requires Gong's "brief" / AI summary content to be available on the
// workspace's plan — if not, this still returns call metadata (title,
// participants, date) even without a narrative summary.

function authHeader() {
  const key = process.env.GONG_ACCESS_KEY;
  const secret = process.env.GONG_ACCESS_KEY_SECRET;
  const token = Buffer.from(`${key}:${secret}`).toString('base64');
  return `Basic ${token}`;
}

async function getRecentCallSummaries({ sinceDays = 7 } = {}) {
  const fromDateTime = new Date(Date.now() - sinceDays * 24 * 60 * 60 * 1000).toISOString();
  const toDateTime = new Date().toISOString();

  const listRes = await fetch(
    `https://api.gong.io/v2/calls?fromDateTime=${fromDateTime}&toDateTime=${toDateTime}`,
    { headers: { Authorization: authHeader() } }
  );
  if (!listRes.ok) {
    throw new Error(`Gong call list failed: ${listRes.status} ${await listRes.text()}`);
  }
  const { calls = [] } = await listRes.json();
  if (calls.length === 0) return [];

  const extensiveRes = await fetch('https://api.gong.io/v2/calls/extensive', {
    method: 'POST',
    headers: { Authorization: authHeader(), 'Content-Type': 'application/json' },
    body: JSON.stringify({
      filter: { callIds: calls.map((c) => c.id) },
      contentSelector: {
        context: 'Extended',
        exposedFields: { content: { brief: true, keyPoints: true } },
      },
    }),
  });
  if (!extensiveRes.ok) {
    throw new Error(`Gong call detail failed: ${extensiveRes.status} ${await extensiveRes.text()}`);
  }
  const { calls: detailedCalls = [] } = await extensiveRes.json();

  return detailedCalls.map((c) => ({
    title: c.metaData?.title || null,
    date: c.metaData?.started || null,
    brief: c.content?.brief || null,
    keyPoints: (c.content?.keyPoints || []).map((k) => k.text),
  }));
}

module.exports = { getRecentCallSummaries };
